feat(core): update puppeteer-core
koishijs/koishi-plugin-puppeteer pull request #35
Opened 2024-01-22 16:39 UTC by idanran

2024-02-13 12:10 UTC, idanran commented
那边在 8 天前推出了 v22.0.0，不确定能不能升。

https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v22.0.0

2024-02-23 18:24 UTC, shigma requested changes

2024-02-23 18:24 UTC, shigma commented on packages/core/package.json
> +    "puppeteer-core": "^21.7.0",
```suggestion
    "puppeteer-core": "^22.2.0",
```

2024-02-24 01:10 UTC, shigma approved these changes

2024-02-24 01:11 UTC, merged